apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if eq .Values.global.database.embedded.enabled false }}
  annotations:
    iam.gke.io/gcp-service-account: {{ $.Values.global.sqlProxyServiceAccount | quote }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "fullname" . }}-operations-scheduler-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - operations.compass
    resources:
      - operations
    verbs:
      - create
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "fullname" . }}-operations-scheduler-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "fullname" . }}-operations-scheduler-role
subjects:
  - kind: ServiceAccount
    name: {{ template "fullname" . }}
    namespace: {{ .Release.Namespace }}

