deployment:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  image:
    pullPolicy: IfNotPresent
  resources: {}
  resourcesCloudsqlProxy: {}
  resourcesIstioProxy:
    requests: {}
    limits: {}
  securityContext: # Set on container level
    runAsUser: 2000
    allowPrivilegeEscalation: false
  dbPool:
    maxOpenConnections: 30
    maxIdleConnections: 2
  strategy: {} # Read more: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  nodeSelector: {}
  external:
    port: 3005
  systemToTemplateMappings: '[{  "Name": "ABAP System",  "SourceKey": ["type"],  "SourceValue": ["abapSys"]},{  "Name": "Non-SAP System",  "SourceKey": ["type"],  "SourceValue": ["nonSAPsys"]},{  "Name": "SAP HANA",  "SourceKey": ["type"],  "SourceValue": ["hana"]}]'
